import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Config from "@components/Config"
import { cookies } from "next/headers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Facebook",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Config value={cookies().getAll()}>{children}</Config>
            </body>
        </html>
    )
}
